modLoader="javafml"
loaderVersion="[4,)"
license="ARR"

[[mods]]
modId="beryl"
version="1.21.1-0.1.3-alpha"
displayName="Beryl"
description="Vulkan shader pipeline for Minecraft."

[[dependencies.beryl]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.beryl]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"

[[dependencies.beryl]]
modId="vulkanmod"
type="required"
versionRange="[0.6.5,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="beryl.mixins.json"
