plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = '1.21.1-0.1.3-alpha'
group = 'net.beryl'

base { archivesName = 'beryl' }

java { toolchain.languageVersion = JavaLanguageVersion.of(21) }

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.fabricmc.net/' }
    mavenCentral()
    flatDir { dirs 'libs' }
}

neoForge {
    version = '21.1.228'

    parchment {
        mappingsVersion = '2024.11.17'
        minecraftVersion = '1.21.1'
    }

    mods {
        beryl { sourceSet sourceSets.main }
    }
}

dependencies {
    implementation(files('libs/vulkanmod-0.6.5-dev.jar'))
    implementation('org.lwjgl:lwjgl-vulkan:3.3.3')
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}
